### ISSUE TITLE
Ubuntu USB

### ISSUE THREAD

**Issue by rhandorf** [cdump/radiacode#7] opened 2022-08-09 14:09 UTC
Howdy do,

I'm trying to run the code here, and this is the output.

python3 -m radiacode-examples.basic
will use USB connection
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rhandorf/code/radicode/radiacode/radiacode-examples/basic.py", line 39, in <module>
    main()
  File "/home/rhandorf/code/radicode/radiacode/radiacode-examples/basic.py", line 17, in main
    rc = RadiaCode()
  File "/home/rhandorf/code/radicode/radiacode/radiacode/radiacode.py", line 29, in __init__
    self.execute(b'\x07\x00', b'\x01\xff\x12\xff')
  File "/home/rhandorf/code/radicode/radiacode/radiacode/radiacode.py", line 46, in execute
    response = self._connection.execute(full_request)
  File "/home/rhandorf/code/radicode/radiacode/radiacode/transports/usb.py", line 19, in execute
    self._device.write(0x1, request)
  File "/usr/local/lib/python3.8/dist-packages/usb/core.py", line 989, in write
    return fn(
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 837, in bulk_write
    return self.__write(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/usr/local/lib/python3.8/dist-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out

I've gone and tried to write some additional code to read any command responses, but it also times out. 

The IO interface does appear to be there:

DEVICE ID 0483:f123 on Bus 001 Address 016 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x201 USB 2.01
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x0483
 idProduct              : 0xf123
 bcdDevice              :  0x200 Device 2.0
 iManufacturer          :    0x1 Scan Electronics
 iProduct               :    0x2 RadiaCode-101
 iSerialNumber          :    0x3 RC-101-003337
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 400 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x4 Custom Config
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :   0xc8 (400 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x5 Custom Interface
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0

**Comment by cdump** [comment] 2023-02-23 13:42
Try to turn-off and turn-on radiacode (there's menu item for that), it helps me in similar usb timeout situation

**Comment by rhandorf** [comment] 2023-02-28 18:00
I've tried that, and the same condition exists. Any other thoughts?

**Comment by ckuethe** [comment] 2023-06-16 03:10
I'm thinking its a firmware error of some sort, since I saw something similar with my RC-102 with firmware 4.x. After some time it would get sufficiently stuck that neither of the windows app or the android app could connect over USB.

**Comment by cdump** [comment] 2023-06-18 13:40
Please check the latest release (v0.2.0)
I didn't find the cause of the problem, but I probably found a [way to solve it](https://github.com/cdump/radiacode/commit/b03afb436995402c433dc00d6aabf23c03427bb0)

**Comment by cdump** [comment] 2023-07-08 08:42
Should be fixed, open new issue if the problem returns

**Closed by cdump** 2023-07-08 08:42 UTC
